import unittest
import numpy as np
# from sklearn.cross_decomposition import CCA # Replace with: from your_module import CustomCCA as CCA
from cca_models import Model, CCA, Regression, model

# Generated by Gemini: https://share.gemini.google/0jgAC61fljSr

class TestCustomCCA(unittest.TestCase):
    r"""
    Unit tests for custom Canonical Correlation Analysis (CCA) implementation.
    
    Theoretical Rationale:
    ----------------------
    To rigorously evaluate the CCA algorithm, we generate synthetic data with 
    a perfectly known canonical correlation structure.
    
    Let X_latent and Noise be matrices of independent draws from $\mathcal{N}(0, 1)$.
    We define target canonical correlations $\rho_i$ and construct Y_latent as:
    
        $Y_{latent} = \rho \cdot X_{latent} + \sqrt{1 - \rho^2} \cdot Noise$
    
    By construction, the exact theoretical canonical correlations between the 
    latent spaces are given by $\rho$. We then horizontally stack independent 
    gaussian noise columns to both X and Y to create the final observable matrices.
    
    A mathematically correct CCA algorithm must:
    1. Recover the true canonical correlations $\rho_i$ from the transformed spaces.
    2. Enforce orthogonality such that $Corr(X_{c, i}, X_{c, j}) = 0$ for $i \neq j$.
    3. Assign near-zero weights to the appended noise dimensions.
    """

    @classmethod
    def setUpClass(cls):
        """Generate the synthetic dataset used across all tests."""
        np.random.seed(42)
        cls.n_samples = 10000 # High sample count to tightly bound empirical variance
        cls.n_components = 2
        
        # 1. Define the theoretical ground-truth correlations
        cls.true_rhos = np.array([0.85, 0.50])
        
        # 2. Generate signal components
        X_latent = np.random.randn(cls.n_samples, cls.n_components)
        Noise_latent = np.random.randn(cls.n_samples, cls.n_components)
        
        # 3. Construct Y signal mathematically coupled to X
        Y_latent = (cls.true_rhos * X_latent) + (np.sqrt(1 - cls.true_rhos**2) * Noise_latent)
        
        # 4. Append noise dimensions to create final matrices
        # X gets 3 noise dimensions (total 5), Y gets 2 noise dimensions (total 4)
        cls.X_noise_dim = 3
        cls.Y_noise_dim = 2
        cls.X = np.hstack([X_latent, np.random.randn(cls.n_samples, cls.X_noise_dim)])
        cls.Y = np.hstack([Y_latent, np.random.randn(cls.n_samples, cls.Y_noise_dim)])
        
        # 5. Fit the custom CCA model
        cls.cca = CCA('test', n_components=cls.n_components)
        cls.Xc, cls.Yc = cls.cca.fit_transform(cls.X, cls.Y)

    def test_canonical_correlations(self):
        """Ensure the algorithm recovers the theoretical correlations."""
        for i in range(self.n_components):
            # Calculate empirical Pearson correlation between transformed components
            empirical_rho = np.corrcoef(self.Xc[:, i], self.Yc[:, i])[0, 1]
            
            # The empirical correlation should match the theoretical rho tightly
            # Tolerance is small (0.02) due to the large sample size (N=10000)
            self.assertAlmostEqual(
                empirical_rho, 
                self.true_rhos[i], 
                delta=0.02,
                msg=f"Failed to recover canonical correlation for component {i}"
            )

    def test_component_orthogonality(self):
        """Ensure successive canonical variates are uncorrelated."""
        if self.n_components > 1:
            # Check correlation between X_c1 and X_c2
            cross_corr_X = np.corrcoef(self.Xc[:, 0], self.Xc[:, 1])[0, 1]
            # Check correlation between Y_c1 and Y_c2
            cross_corr_Y = np.corrcoef(self.Yc[:, 0], self.Yc[:, 1])[0, 1]
            
            self.assertAlmostEqual(
                cross_corr_X, 0.0, delta=0.02, 
                msg="Transformed X components are not orthogonal."
            )
            self.assertAlmostEqual(
                cross_corr_Y, 0.0, delta=0.02, 
                msg="Transformed Y components are not orthogonal."
            )

    def test_noise_feature_weights(self):
        """Ensure the algorithm correctly ignores uncoupled noise dimensions."""
        # Note: Depending on your custom implementation, weights might be stored 
        # as x_weights_ / y_weights_ or x_rotations_ / y_rotations_. 
        # Adjust the attribute names below to match your code.
        
        if hasattr(self.cca, 'x_weights_'):
            x_weights = self.cca.x_weights_
            y_weights = self.cca.y_weights_
            
            # The weights for the appended noise features (indices 2, 3, 4 for X) 
            # should be significantly smaller than the signal features (indices 0, 1)
            signal_power_X = np.linalg.norm(x_weights[:self.n_components, :])
            noise_power_X = np.linalg.norm(x_weights[self.n_components:, :])
            
            self.assertGreater(
                signal_power_X, noise_power_X * 10,
                msg="Model is assigning too much weight to X noise dimensions."
            )

if __name__ == '__main__':
    unittest.main()